openapi: '3.0.1'

info:
  title: User
  version: "1"
  description: User resources

servers:
  - url: http://localhost:8080/api
    description: local server

paths:

  /user:
    post:
      summary: Save User
      operationId: saveUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'

  /user/{id}:
    get:
      summary: Get user by id
      operationId: getUserById
      parameters:
        - name: id
          in: path
          description: Unique Id of An User
          required: true
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDTO'

components:
  schemas:
    UserDTO:
      type: object
      description: Data element for user
      required:
        - email
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
        firstName:
          type: string
          minLength: 3
          maxLength: 10
        lastName:
          type: string